### ISSUE TITLE
Hard time finding some items for BOM

### ISSUE THREAD

**Issue by amchagas** [Sussex-Neuroscience/olfactory-stimulator#1]
I'm having a bit of a hard time finding the following items:

glas tube 7 mm ID, 10 mm OD, 80 mm length 
glas tube 4 mm ID, 7 mm OD, 80 mm length
O-ring seal, silicon, I.D. 8 mm, O.D. 10 mm
O-ring seal, silicon, I.D. 12 mm, O.D. 15 mm

Any help here would be much appreciated!

**Comment by mariopan** [comment]
Hi Andre, 
I found these solutions for the O-ring: 
http://www.bearingshopuk.co.uk/8-x-1mm-silicone-70-o-ring-35235
http://www.bearingshopuk.co.uk/12-1-x-1-6mm-silicone-70-o-ring-36856
The second one is 12.1 instead of 12mm, good enough?


For the glass tubes, I found this company:
http://www.glass-solutions.com/wp-content/uploads/2010/12/schott-tubing_brochure_duran_english-en.pdf
I send them an email asking for a quote.
